server:
  port: ${PORT:8080}
  tomcat:
    uri-encoding: UTF-8
spring:
  threads:
    virtual:
      enabled: true
  cache:
    type: redis
  mongodb:
    uri: ${mongodUri}
  data:
    redis:
      database: 0
      host: ${redisHost}
      port: ${redisPort}
      password: ${redisPassword}
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
  quartz:
    cron: 0 0 */2 * * ?
    jobName: openDataTask
    jobGroupName: OpenDataTaskImpl
  boot:
    aes:
      key: ${aesKey}
    openCWB:
      cwbUrl: ${weatherForecast}
  line:
    replyUrl: ${replyUrl}
    channelSecret: ${channelSecret}
    channelToken: ${channelToken}

logging:
  level:
    root: info
    org:
      springframework:
        web:
          client:
            RestTemplate: info
