server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  data:
    mongodb:
      uri: ${sm://mongodUri}
  cloud:
    gcp:
      secretmanager:
        enabled: true
  quartz:
    cron: 0 0 9 * * ?
    jobName: pushTask
    jobGroupName: pushAllTask
  boot:
    aes:
      key: ${sm://aesKey}
    SecretManager:
      key: ${sm://serviceAccountKey}
    openCWB:
#       36小時 全台預報 location locationName 臺北市
      datastore: ${sm://allWeatherForecast}
#      臺北市 各區預報
      taipei: ${sm://taipeiWeatherForecast}
      newTaipei: ${sm://newTaipeiWeatherForecast}
  line:
    replyUrl: ${sm://replyUrl}
    channelSecret: ${sm://channelSecret}
    channelToken: ${sm://channelToken}

logging:
    level:
        com.opendata.chatbot: trace
        com.opendata.chatbot.service: trace
        org:
            springframework:
                web:
                    client:
                        RestTemplate: info